version: '3.1'

services:

  postgres:
    container_name: vector_db
    image: ankane/pgvector
    command: postgres -c 'max_connections=200'
    ports:
      - 5432:5432
    restart: always
    environment:
       - POSTGRES_HOST_AUTH_METHOD=trust
       - POSTGRES_PASSWORD=mypass
       - POSTGRES_USER=dbuser
       - POSTGRES_DB=hatchDB
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

