root = "." 
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/process-documents-worker src/process-documents-worker/*.go"
bin = "tmp/app"

full_bin = "./tmp/process-documents-worker"
log = "air_errors.log"
include_ext = ["go"]
exclude_dir = ["tmp"]
delay = 1000

[log]
time = true

[misc]
clean_on_exit = true